"""Build the downloadable Markdown follow-up note (roadmap W2 deliverable).

A debrief ends with three artifacts: the ledger (the raw record), the history
file (cross-debrief commitments), and this note - a human-readable summary the
investor can keep, forward, or file per company. It is generated from one
ledger session, so no extra state is needed:

    GET /api/note?session=<id>&company=<name>

with session defaulting to the most recent ledger session. company is optional
and only used for the title and the download filename.
"""

from typing import Optional

from history_from_ledger import load_ledger, pick_session, slugify


def _stamp(seconds) -> str:
    if seconds is None:
        return "--:--"
    total = max(0, int(float(seconds)))
    return f"{total // 60:02d}:{total % 60:02d}"


def build_note(session_id: str, session: dict, company: str = "") -> str:
    """Render one ledger session as a Markdown follow-up note."""
    name = (company or "").strip() or "Unnamed company"
    events = sorted(
        (session.get("events") or []),
        key=lambda e: (e.get("at_seconds") is None, e.get("at_seconds") or 0),
    )
    evidence = [e for e in events if e.get("tool") == "log_evidence"]
    actions = [e for e in events if e.get("tool") == "add_action_item"]
    escalated = [e for e in evidence if e.get("escalation")]

    out = [
        f"# Follow-up note — {name}",
        "",
        f"- Session: `{session_id}`",
        f"- Debriefed at: {session.get('started_at') or 'unknown'}",
        "",
    ]

    out.append("## Red flags (escalation checklist)")
    out.append("")
    if escalated:
        for e in escalated:
            dim = e.get("dimension") or ""
            signal = e.get("signal") or ""
            quote = e.get("quote") or ""
            out.append(f"- **{signal}** ({dim}) — “{quote}” "
                       f"[{_stamp(e.get('at_seconds'))}]")
    else:
        out.append("None recorded this session.")
    out.append("")

    out.append("## Risk signals")
    out.append("")
    if evidence:
        out.append("| Time | Dimension | Signal | Quote |")
        out.append("|---|---|---|---|")
        for e in evidence:
            quote = (e.get("quote") or "").replace("|", "\\|")
            out.append(f"| {_stamp(e.get('at_seconds'))} "
                       f"| {e.get('dimension') or ''} "
                       f"| {e.get('signal') or ''} "
                       f"| “{quote}” |")
    else:
        out.append("None recorded this session.")
    out.append("")

    out.append("## Open action items")
    out.append("")
    if actions:
        for e in actions:
            owner = e.get("owner") or "unassigned"
            deadline = e.get("deadline") or "no deadline"
            out.append(f"- [ ] {e.get('task') or '(untitled)'} "
                       f"— {owner}, due {deadline}")
    else:
        out.append("None recorded this session.")
    out.append("")

    out.append("---")
    out.append("Generated by Second Listen — the post-investment debrief partner.")
    return "\n".join(out)


def note_for_session(session_id: Optional[str] = None,
                     company: str = "") -> tuple[str, str]:
    """Pick a ledger session and render it. Returns (session_id, markdown)."""
    ledger = load_ledger()
    sid, session = pick_session(ledger, session_id or "")
    return sid, build_note(sid, session, company)


def filename_for(company: str, session_id: str) -> str:
    name = slugify(company) if (company or "").strip() else ""
    return (name or f"session-{session_id[-8:]}") + "-follow-up.md"
